alert("In this experiment we will measure your response time. You will be shown a series of simple math equations. Answer these equations as quickly and accurately as you can.");
let start = Date.now();
let answer1 = prompt("What is 4 + 5?");
let end = Date.now();
let responseTime = (end - start) / 1000;
alert("You answered " + answer1 + " in " + responseTime + " seconds");
start = Date.now();
answer = prompt("What is 6 + 7?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer + " in " + responseTime + " seconds");
start = Date.now();
answer = prompt("What is 2 + 9?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer + " in " + responseTime + " seconds");
alert("Thank you for your participation!");
