// Initialize an empty array you will populate with your conditions
let practice = [
    { example: 'hgfj' },
    { example: 'pokl' },
    { example: 'gqyu' },
]
let words = [

    { word: 'cube', valence: 'neutral' },
    { word: 'read', valence: 'neutral' },
    { word: 'boat', valence: 'neutral' },
    { word: 'tree', valence: 'neutral' },
    { word: 'land', valence: 'neutral' },
    { word: 'city', valence: 'neutral' },
    { word: 'ship', valence: 'neutral' },
    { word: 'lake', valence: 'neutral' },
    { word: 'idea', valence: 'neutral' },
    { word: 'vile', valence: 'neutral' },
    { word: 'pain', valence: 'threatening' },
    { word: 'fear', valence: 'threatening' },
    { word: 'hate', valence: 'threatening' },
    { word: 'kill', valence: 'threatening' },
    { word: 'hell', valence: 'threatening' },
    { word: 'evil', valence: 'threatening' },
    { word: 'bomb', valence: 'threatening' },
    { word: 'died', valence: 'threatening' },
    { word: 'rage', valence: 'threatening' },
    { word: 'glee', valence: 'positive' },
    { word: 'warm', valence: 'positive' },
    { word: 'kind', valence: 'positive' },
    { word: 'love', valence: 'positive' },
    { word: 'hope', valence: 'positive' },
    { word: 'hero', valence: 'positive' },
    { word: 'cure', valence: 'positive' },
    { word: 'wise', valence: 'positive' },
    { word: 'sexy', valence: 'positive' },
    { word: 'idea', valence: 'positive' },
];
